//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDoCu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public int Price { get; set; }
        public string Picture { get; set; }
        public System.DateTime PostingDate { get; set; }
        public Nullable<bool> Available { get; set; }
        public int UserID { get; set; }
        public string Location { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
